# WS SAST Scan

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    curl -LJO https://downloads-sast.mend.io/sast-cli/windows/mendsastcli.exe
    echo  WS SAST CLI downloaded successfully
    mendsastcli.exe --dir ./ --name=$(Build.Repository.Name)$(Build.SourceBranchName) --app $(System.TeamProject) --incr
  env:
    SAST_ORGANIZATION: $(ORGANIZATION)
    SASTCLI_TOKEN: $(CLI_TOKEN)
    SAST_SERVER: https://sast-app.whitesourcesoftware.com
    SASTCLI_TARGET_APPLICATION: DotNET-Demo
  displayName: 'WS SAST Scan'
