# Mend SAST Scan

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    mkdir C:\mend\cli && curl https://downloads.mend.io/cli/windows_amd64/mend.exe -o C:\mend\cli\mend.exe
    echo  Mend CLI downloaded successfully
    dir "c:\users"
    echo  Mend CLI downloaded successfully 2
    C:\mend\cli\mend.exe sast -d ./ --app DotNET-Demo --name MyBranch
  env:
    MEND_SAST_SERVER_URL: https://sast.mend.io/sast/
    MEND_SAST_API_TOKEN: $(MEND_SAST_API)
    MEND_SAST_ORGANIZATION: $(MEND_SAST_ORGANIZATION_UUID)
  displayName: 'Mend SAST Scan'
- publish: c:\users\VssAdministrator\.mend\logs
  artifact: "Mend CLI Logs"