# WS SAST Scan

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    curl -LJO https://downloads-demo.whitesourcesoftware.com/sast-cli/windows/wscli.exe
    echo  WS SAST CLI downloaded successfully
    wscli.exe --dir ./ --name=$(Build.Repository.Name)_$(Build.SourceBranchName) --baseline=true 
  env:
    SAST_ORGANIZATION: $(ORGANIZATION)
    SASTCLI_TOKEN: $(CLI_TOKEN)
    SAST_SERVER: https://sast-demo.whitesourcesoftware.com
    SASTCLI_TARGET_APPLICATION: DotNET-Demo
  displayName: 'WS SAST Scan'
