# WS SAST Scan

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    curl -LJO https://downloads.mend.io/cli/windows_amd64/mend.exe
    echo  Mend CLI downloaded successfully
    mend.exe sast -d ./ --app DotNET-Demo --name MyBranch
  env:
    MEND_SAST_SERVER_URL: https://sast.whitesourcesoftware.com
    MEND_SAST_API_TOKEN: $(MEND_SAST_API)
  displayName: 'WS SAST Scan'
